version: '3'

services:
  anyway:
    build: .
    container_name: anyway
    image: hasadna/anyway:latest
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL=postgresql://anyway:anyway@db/anyway
      - FLASK_ENV=development
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_KEY
      - TWITTER_ACCESS_SECRET
      - GOOGLE_APPLICATION_CREDENTIALS=GOOGLE_APPLICATION_CREDENTIALS_KEY.json
    volumes:
      - .:/anyway
    restart: always
    depends_on:
      - db

  db:
    build: db_docker
    container_name: db
    environment:
      - POSTGRES_PASSWORD=anyway
      - POSTGRES_USER=anyway
      - POSTGRES_DB=anyway
      - DB_DUMP_PATH=/tmp/anyway_public.pgdump
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "9876:5432"
    restart: always

  jupyter:
    build: jupyter
    container_name: jupyter
    ports:
      - "8888:8888"   
    volumes: 
      - "./jupyter/work:/home/jovyan/work"
    restart: always 

volumes:
  db_data:
